/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gui;

/**
 *
 * @author ADMIN
 */
public class ClientWindows extends javax.swing.JFrame {

    /**
     * Creates new form ClientWindows
     */
    public ClientWindows() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        LoginDashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnStart = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MainDashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtusrnme = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtnamepc = new javax.swing.JTextField();
        txtbiaya = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        LoginDashboard.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("HomeInet.id");
        LoginDashboard.add(jLabel4);
        jLabel4.setBounds(230, 60, 87, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Username");
        LoginDashboard.add(jLabel1);
        jLabel1.setBounds(130, 140, 59, 15);

        jLabel3.setText("Welcome , Please login first ... ");
        LoginDashboard.add(jLabel3);
        jLabel3.setBounds(130, 100, 149, 14);

        BtnStart.setBackground(new java.awt.Color(121, 204, 231));
        BtnStart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnStart.setForeground(new java.awt.Color(255, 255, 255));
        BtnStart.setText("Start");
        LoginDashboard.add(BtnStart);
        BtnStart.setBounds(131, 200, 280, 31);
        LoginDashboard.add(txtUsername);
        txtUsername.setBounds(130, 160, 280, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dasboard Client Billing.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        LoginDashboard.add(jLabel2);
        jLabel2.setBounds(-6, -6, 540, 370);

        MainPanel.add(LoginDashboard, "card2");

        MainDashboard.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("HomeInet.id");
        MainDashboard.add(jLabel5);
        jLabel5.setBounds(250, 90, 120, 17);
        MainDashboard.add(txtusrnme);
        txtusrnme.setBounds(170, 130, 180, 30);
        MainDashboard.add(txttime);
        txttime.setBounds(170, 170, 180, 30);

        jButton2.setBackground(new java.awt.Color(251, 79, 79));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Stop");
        MainDashboard.add(jButton2);
        jButton2.setBounds(170, 210, 240, 30);

        txtnamepc.setBackground(new java.awt.Color(180, 234, 246));
        txtnamepc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamepcActionPerformed(evt);
            }
        });
        MainDashboard.add(txtnamepc);
        txtnamepc.setBounds(350, 130, 60, 30);

        txtbiaya.setBackground(new java.awt.Color(180, 234, 246));
        MainDashboard.add(txtbiaya);
        txtbiaya.setBounds(350, 170, 60, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dasboard Client Billing.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        MainDashboard.add(jLabel6);
        jLabel6.setBounds(-6, -6, 580, 400);

        MainPanel.add(MainDashboard, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamepcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamepcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamepcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnStart;
    private javax.swing.JPanel LoginDashboard;
    private javax.swing.JPanel MainDashboard;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtbiaya;
    private javax.swing.JTextField txtnamepc;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txtusrnme;
    // End of variables declaration//GEN-END:variables
}
