/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gui;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.JRootPane;
import javax.swing.border.Border;

/**
 *
 * @author rickyandhi
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        signInPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        dashboardTabsPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        dashboardContentPanel = new javax.swing.JPanel();
        dashboardContentMonitorPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dashboardContentHistoryPanel = new javax.swing.JPanel();
        dashboardContentSettingPanel = new javax.swing.JPanel();
        dashboardContentProfilePanel = new javax.swing.JPanel();
        dashboardContentLogoutPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(177, 224, 239));
        mainPanel.setLayout(new java.awt.CardLayout());

        signInPanel.setBackground(new java.awt.Color(255, 255, 255));
        signInPanel.setLayout(new java.awt.GridLayout());

        jPanel3.setBackground(new java.awt.Color(180, 234, 246));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        signInPanel.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Sign In");

        jTextField1.setBackground(new java.awt.Color(245, 245, 245));
        jTextField1.setBorder(null);

        jTextField2.setBackground(new java.awt.Color(245, 245, 245));
        jTextField2.setBorder(null);

        jToggleButton1.setBackground(new java.awt.Color(180, 234, 246));
        jToggleButton1.setForeground(new java.awt.Color(67, 89, 96));
        jToggleButton1.setText("Login");
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(159, 159, 159))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        signInPanel.add(jPanel2);

        mainPanel.add(signInPanel, "cardSignIn");

        dashboardTabsPanel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardTabsPanel.setLayout(new java.awt.GridLayout(1, 5));

        jButton1.setBackground(new java.awt.Color(180, 234, 246));
        jButton1.setIcon(new javax.swing.ImageIcon("/home/rickyandhi/Downloads/rsz_1rsz_1rsz_illust58-4862-01.jpg")); // NOI18N
        jButton1.setText("Monitor");
        dashboardTabsPanel.add(jButton1);

        jButton2.setBackground(new java.awt.Color(180, 234, 246));
        jButton2.setText("History");
        dashboardTabsPanel.add(jButton2);

        jButton3.setBackground(new java.awt.Color(180, 234, 246));
        jButton3.setText("Setting");
        dashboardTabsPanel.add(jButton3);

        jButton4.setBackground(new java.awt.Color(180, 234, 246));
        jButton4.setText("Profile");
        dashboardTabsPanel.add(jButton4);

        jButton5.setBackground(new java.awt.Color(180, 234, 246));
        jButton5.setText("Log Out");
        dashboardTabsPanel.add(jButton5);

        dashboardContentPanel.setBackground(new java.awt.Color(180, 234, 246));
        dashboardContentPanel.setLayout(new java.awt.CardLayout());

        dashboardContentMonitorPanel.setBackground(new java.awt.Color(180, 234, 246));

        jLabel4.setText("Data Monitoring Client");

        javax.swing.GroupLayout dashboardContentMonitorPanelLayout = new javax.swing.GroupLayout(dashboardContentMonitorPanel);
        dashboardContentMonitorPanel.setLayout(dashboardContentMonitorPanelLayout);
        dashboardContentMonitorPanelLayout.setHorizontalGroup(
            dashboardContentMonitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardContentMonitorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(773, Short.MAX_VALUE))
        );
        dashboardContentMonitorPanelLayout.setVerticalGroup(
            dashboardContentMonitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardContentMonitorPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        dashboardContentPanel.add(dashboardContentMonitorPanel, "card2");

        javax.swing.GroupLayout dashboardContentHistoryPanelLayout = new javax.swing.GroupLayout(dashboardContentHistoryPanel);
        dashboardContentHistoryPanel.setLayout(dashboardContentHistoryPanelLayout);
        dashboardContentHistoryPanelLayout.setHorizontalGroup(
            dashboardContentHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        dashboardContentHistoryPanelLayout.setVerticalGroup(
            dashboardContentHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        dashboardContentPanel.add(dashboardContentHistoryPanel, "card3");

        javax.swing.GroupLayout dashboardContentSettingPanelLayout = new javax.swing.GroupLayout(dashboardContentSettingPanel);
        dashboardContentSettingPanel.setLayout(dashboardContentSettingPanelLayout);
        dashboardContentSettingPanelLayout.setHorizontalGroup(
            dashboardContentSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        dashboardContentSettingPanelLayout.setVerticalGroup(
            dashboardContentSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        dashboardContentPanel.add(dashboardContentSettingPanel, "card4");

        javax.swing.GroupLayout dashboardContentProfilePanelLayout = new javax.swing.GroupLayout(dashboardContentProfilePanel);
        dashboardContentProfilePanel.setLayout(dashboardContentProfilePanelLayout);
        dashboardContentProfilePanelLayout.setHorizontalGroup(
            dashboardContentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        dashboardContentProfilePanelLayout.setVerticalGroup(
            dashboardContentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        dashboardContentPanel.add(dashboardContentProfilePanel, "card5");

        javax.swing.GroupLayout dashboardContentLogoutPanelLayout = new javax.swing.GroupLayout(dashboardContentLogoutPanel);
        dashboardContentLogoutPanel.setLayout(dashboardContentLogoutPanelLayout);
        dashboardContentLogoutPanelLayout.setHorizontalGroup(
            dashboardContentLogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        dashboardContentLogoutPanelLayout.setVerticalGroup(
            dashboardContentLogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        dashboardContentPanel.add(dashboardContentLogoutPanel, "card6");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dashboardTabsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(dashboardContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardPanelLayout.createSequentialGroup()
                    .addComponent(dashboardTabsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 311, Short.MAX_VALUE)))
        );

        mainPanel.add(dashboardPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardContentHistoryPanel;
    private javax.swing.JPanel dashboardContentLogoutPanel;
    private javax.swing.JPanel dashboardContentMonitorPanel;
    private javax.swing.JPanel dashboardContentPanel;
    private javax.swing.JPanel dashboardContentProfilePanel;
    private javax.swing.JPanel dashboardContentSettingPanel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel dashboardTabsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel signInPanel;
    // End of variables declaration//GEN-END:variables
}
